### ISSUE TITLE
Poetry: failure to install

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/modelica-builder#40]
## context
Packages which use modelica-builder, seems to fail when updating the package -- this example is from the geojson-modelica-translator:

```
Package operations: 0 installs, 1 update, 0 removals

  • Updating modelica-builder (0.1.1 -> 0.2.0): Failed

  EnvCommandError

  Command ['/Users/tedsummer/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator--NBSD__x-py3.7/bin/pip', 'install', '--no-deps', '-U', '/Users/tedsummer/Library/Caches/pypoetry/artifacts/ee/96/51/30434b0ab28523fa577786a7f585a41fd18419b218cb088982e3d2e9a5/modelica-builder-0.2.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/tedsummer/Library/Caches/pypoetry/artifacts/ee/96/51/30434b0ab28523fa577786a7f585a41fd18419b218cb088982e3d2e9a5/modelica-builder-0.2.0.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /Users/tedsummer/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator--NBSD__x-py3.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j4/_lf59l092rz1lb9q9dlh9md40000gn/T/pip-req-build-7g2hi2di/setup.py'"'"'; __file__='"'"'/private/var/folders/j4/_lf59l092rz1lb9q9dlh9md40000gn/T/pip-req-build-7g2hi2di/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/j4/_lf59l092rz1lb9q9dlh9md40000gn/T/pip-pip-egg-info-idqeteop
           cwd: /private/var/folders/j4/_lf59l092rz1lb9q9dlh9md40000gn/T/pip-req-build-7g2hi2di/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/j4/_lf59l092rz1lb9q9dlh9md40000gn/T/pip-req-build-7g2hi2di/setup.py", line 14, in <module>
          from management.update_licenses import UpdateLicenses
      ImportError: cannot import name 'UpdateLicenses' from 'management.update_licenses' (/Users/tedsummer/Development/Projects/NREL/geojson-modelica-translator/management/update_licenses.py)
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 20.2.2; however, version 21.2.4 is available.
  You should consider upgrading via the '/Users/tedsummer/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator--NBSD__x-py3.7/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):


Failed to add packages, reverting the pyproject.toml file to its original content.
```

## task
Fix this and create patch release

**Comment by macintoshpie** [comment]
For future reference, it looks like it was trying to import the class from the GMT's update_licenses.py file... not sure why that's happening. Workaround is to just avoid importing this

```
ImportError: cannot import name 'UpdateLicenses' from 'management.update_licenses' (/Users/tedsummer/Development/Projects/NREL/geojson-modelica-translator/management/update_licenses.py
```
